services:
  hindsight:
    image: ghcr.io/vectorize-io/hindsight:latest
    container_name: hindsight
    pull_policy: always
    restart: unless-stopped
    ports:
      - "8888:8888"
      - "9999:9999"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    environment:
      HINDSIGHT_API_LLM_PROVIDER: openai
      HINDSIGHT_API_LLM_MODEL: Qwen3.6-35B-A3B-MTP-Q4
      HINDSIGHT_API_LLM_BASE_URL: http://host.docker.internal:7778/v1
      # HINDSIGHT_API_LLM_BASE_URL: http://128.1.1.48:7778/v1
      HINDSIGHT_API_LLM_API_KEY: dummy

      # 外部 Embedding 接口
      HINDSIGHT_API_EMBEDDINGS_PROVIDER: openai
      HINDSIGHT_API_EMBEDDINGS_OPENAI_BASE_URL: http://host.docker.internal:8888/v1
      HINDSIGHT_API_EMBEDDINGS_OPENAI_API_KEY: dummy
      HINDSIGHT_API_EMBEDDINGS_OPENAI_MODEL: bge-m3

      # 外部 Reranker 接口
      HINDSIGHT_API_RERANK_PROVIDER: openai
      HINDSIGHT_API_RERANK_OPENAI_BASE_URL: http://host.docker.internal:8888/v1
      HINDSIGHT_API_RERANK_OPENAI_API_KEY: dummy
      HINDSIGHT_API_RERANK_OPENAI_MODEL: bge-reranker-v2-m3

      HF_ENDPOINT: https://hf-mirror.com
      HF_HOME: /home/hindsight/.cache/huggingface
      HINDSIGHT_HF_CACHE: /home/hindsight/.cache/huggingface
    volumes:
      - ./data:/home/hindsight/.pg0
      - ./hf_cache:/home/hindsight/.cache/huggingface
